### ISSUE TITLE
Wie lässt sich die Menge pro Wippenschlag errechnet?

### ISSUE THREAD

**Issue by josefglatz** [HMSteve/HB-UNI-Sen-RainCounter#1]
Mich würde das interessieren, da ich einen Regenmesser aus dem Hause China ergattern konnte.

mit lieben Dank im Voraus

**Comment by HMSteve** [comment]
Eine bekannte Menge Wasser (einige 100 ml) sehr langsam in den Regenmesser gießen und die Wippenschlaege zählen. Per Dreisatz erhält man Regenmenge pro Wippenschlag. Die Menge in l geteilt durch die Fläche der Öffnung des Regenmessers in qm ergibt mm Regen pro Wippenschlag.

**Comment by josefglatz** [comment]
Herzlichsten Dank!!!!!!
